default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: <%= ENV['CYPRESS'] ? 'Cards4Trade_test' : 'Cards4Trade_development' %>

test:
  <<: *default
  database: Cards4Trade_test

development:
  <<: *default
  database: qr_code_generator_usage_dev

production:
  <<: *default
  database: qr_code_generator_usage_dev

